import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider 
      appearance={{
        layout:{
          logoImageUrl:"/icons/logo.svg",
          socialButtonsVariant:"iconButton"
        },
        variables:{
          colorText: "#fff",
          colorPrimary:"0E78F9",
          colorBackground:"#1c1f2e",
          colorInputBackground:"#252a41",
          colorInputText:"#fff"
        }
      }}
      >
        <body className={`${inter.variable} antialiased bg-2`}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
